### ISSUE TITLE
AWS credentials

### ISSUE THREAD

**Issue by gu1ll0me** [brave/go-sync#47]
Is it mandatory to have a valid AWS credentials to self-host the sync server? I'm getting this error message when the Brave client try to initialize connection. Thank you.

```
"error creating server defined unique entitiies: error checking if entity with a server tag existed: error calling GetItem to check if server tag existed: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

**Comment by bsclifton** [comment]
cc: @yrliou @darkdh

**Comment by yrliou** [comment]
Closing the issue since we do not need that to self-host the sync server, please feel free to comment here if you still have issues on this @gu1ll0me, thanks!

**Comment by gu1ll0me** [comment]
Using the credential below in the docker-compose file solved my problem. Thank you for your help @yrliou.

```
AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```
