### ISSUE TITLE
ready to go docker image?

### ISSUE THREAD

**Issue by psychowood** [brave/go-sync#51]
Do you have plans to release a prebuilt docker image, or at least a docker-compose file, to easen personal installations?

**Comment by amirsaber** [comment]
Do you find something missing from the current compose file [here](https://github.com/brave/go-sync/blob/master/docker-compose.yml) ?

**Comment by psychowood** [comment]
Nope, I missed the file itself 😒

Will try that as soon as Brave for Android will support custom sync server url.

**Comment by yrliou** [comment]
Closing this issue as we provides docker-compose files in the repo.
