### ISSUE TITLE
Timestamp endpoint changes to match client changes

### ISSUE THREAD

**Issue by yrliou** [brave/go-sync#9]
To avoid patching in brave sync client, server need to do bellow changes:
1) Use `POST /timestamp` instead of `GET /timestamp`, and the request body could be ignored.
2) Change the json response:
```
type TimestampResponse struct {
-       Timestamp string `json:"timestamp"`
+       Timestamp string `json:"access_token"`
        ExpiresIn int64  `json:"expires_in"`
 }
```

cc @darkdh

**Comment by darkdh** [comment]
The specific file is `google_apis/gaia/oauth2_access_token_fetcher_impl.cc`
